apiVersion: apps/v1
kind: Deployment
metadata:
  name: track3-app
  namespace: aagamu
spec:
  template:
    spec:
      containers:
      - name: track3-app
        envFrom:
        - configMapRef:
            name: track3-app-env
